### ISSUE TITLE
HW-4 solved

### ISSUE THREAD

**Issue by syftalent** [syftalent/dist-sys-exercises-1#1]
Link:https://github.com/syftalent/dist-sys-exercises-1/releases/tag/lec-4-solved

Yifei

**Comment by wenhuizhang** [comment]
details here https://github.com/syftalent/dist-sys-exercises-1/commit/6b182822d4188afe75396eaf2262cb3323b7e638

pls remind me for extra credits for this HW, as there is no regulations on how much should be added now  officially. 

thanks for your patience, and great job!

wenhui
